services:
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./client:/app
    ports:
      - "6969:3000"

  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    volumes:
      - ./server:/app
    ports:
      - "6968:5000"
