version: "3"

services:
  client:
    restart: always
    env_file:
      - ./client/.env.production
    build:
      context: ./client
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: "production"
    volumes:
      - ./client:/app


  server:
    restart: always
    build:
      context: ./server
      dockerfile: ./Dockerfile
    volumes:
      - ./server:/app

  nginx:
    restart: always
    build: nginx
    ports:
      - 80:80
    depends_on:
      - client
      - server
