services:
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: "production"
    volumes:
      - ./client:/app

  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    volumes:
      - ./server:/app

  nginx:
    build: nginx
    ports:
      - 80:80
    depends_on:
      - client
      - server
