services:
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./client:/app

  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    volumes:
      - ./server:/app

  nginx:
    build: nginx
    ports:
      - 6969:80
    depends_on:
      - client
      - server
